services:
  nginx-gateway:
    image: nginx:stable
    container_name: nginx-gateway
    ports:
      - "5001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
    depends_on:
      - translator
      - auth-service-1
      - clients-service-1
      - products-service-1
      - inventory-service-1
      - inventory-service-2
      - inventory-service-3
      - inventory-service-4
      - inventory-service-5
    networks:
      - censudex-net

  # HTTP gRPC Translator Service
  translator:
    build:
      context: ./translator
      dockerfile: Dockerfile
    container_name: translator
    ports:
      - "5010:5010"
    environment:
      - ASPNETCORE_URLS=http://+:5010
    env_file:
      - .env
    networks:
      - censudex-net

  # Auth Service Instances (3) for load balance
  auth-service-1:
    build: ../censudex-auth  
    container_name: auth-service-1
    env_file:
      - ../censudex-auth/.env  
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - INSTANCE_ID=1
    networks:
      - censudex-net

  # Clients Service Instances (3) for load balance
  clients-service-1:
    build:
      context: ../censudex-clients   
      dockerfile: Dockerfile
    container_name: clients-service-1
    env_file:
      - ../censudex-clients/.env  
    environment:
      - INSTANCE_ID=1
    networks:
      - censudex-net

  products-service-1:
    build:
      context: ../censudex-products   
      dockerfile: Dockerfile
    container_name: products-service-1
    env_file:
      - ../censudex-products/.env  
    environment:
      - INSTANCE_ID=1
    networks:
      - censudex-net

networks:
  censudex-net:
    driver: bridge