services:
  nginx-gateway:
    image: nginx:stable
    container_name: nginx-gateway
    ports:
      - "5001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
    depends_on:
      - auth-service-1
      - auth-service-2
      - auth-service-3
      - clients-service-1
      - clients-service-2
      - clients-service-3
    networks:
      - censudex-net

  # Auth Service Instances (3) for load balance
  auth-service-1:
    build: ../censudex-auth  
    container_name: auth-service-1
    env_file:
      - ../censudex-auth/.env  
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - INSTANCE_ID=1
    networks:
      - censudex-net

  auth-service-2:
    build: ../censudex-auth  
    container_name: auth-service-2
    env_file:
      - ../censudex-auth/.env  
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - INSTANCE_ID=2
    networks:
      - censudex-net

  auth-service-3:
    build: ../censudex-auth  
    container_name: auth-service-3
    env_file:
      - ../censudex-auth/.env  
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - INSTANCE_ID=3
    networks:
      - censudex-net

  # Clients Service Instances (3) for load balance
  clients-service-1:
    build:
      context: ../censudex-clients   
      dockerfile: Dockerfile
    container_name: clients-service-1
    env_file:
      - ../censudex-clients/.env  
    environment:
      - ASPNETCORE_URLS=http://+:5003
      - INSTANCE_ID=1
    networks:
      - censudex-net

  clients-service-2:
    build:
      context: ../censudex-clients   
      dockerfile: Dockerfile
    container_name: clients-service-2
    env_file:
      - ../censudex-clients/.env  
    environment:
      - ASPNETCORE_URLS=http://+:5003
      - INSTANCE_ID=2
    networks:
      - censudex-net

  clients-service-3:
    build:
      context: ../censudex-clients   
      dockerfile: Dockerfile
    container_name: clients-service-3
    env_file:
      - ../censudex-clients/.env  
    environment:
      - ASPNETCORE_URLS=http://+:5003
      - INSTANCE_ID=3
    networks:
      - censudex-net

networks:
  censudex-net:
    driver: bridge